apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-debridnest
  labels:
    app.kubernetes.io/name: debridnest
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  api-token: {{ required "secret.apiToken is required" .Values.secret.apiToken | quote }}
